name: resultx
description: A Future Aware Result class to grcefully handle success and error and their Futures without the need to await on each step
version: 1.0.5
repository: https://github.com/fahidsarker/dart_results

environment:
  sdk: ^3.5.3

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
